apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-b-namespace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jvdbeemt/argocd.git
    targetRevision: HEAD
    path: applications/mariadb/customer-b/namespace
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  syncOptions:
    - Validate=false
    - PruneLast=false
  # Make sure it syncs before the Helm chart
  syncWave: "-1"

