apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator-customer-b
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mariadb-operator.github.io/mariadb-operator
    chart: mariadb-operator
    targetRevision: 0.0.21
    helm:
      releaseName: mariadb-operator
      values: |
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: customer-b-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true

